# [Python Reference Link](http://www.data8.org/sp20/python-reference.html)
*Run the cell below so that we can set our modules up*

In [1]:
import numpy as np
from datascience import *
from IPython.display import YouTubeVideo
import math 

# These lines do some fancy plotting magic.
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

# Bootstrapping Samples Demo

In [2]:
num_brown = 4
num_blue = 29
num_yellow = 19
num_green = 14
num_orange = 29
num_red = 11

m_m_bag = Table().with_columns('Colors',make_array('Brown','Blue','Yellow','Green','Orange','Red'),
                               'Count (from pic)',make_array(num_brown,num_blue,num_yellow,num_green,num_orange,num_red))
m_m_bag

Colors | Count (from pic)
Brown  | 4
Blue   | 29
Yellow | 19
Green  | 14
Orange | 29
Red    | 11

In [4]:
color_list = (['Brown']*num_brown + ['Blue']*num_blue + ['Yellow']*num_yellow + 
              ['Green']*num_green + ['Orange']*num_orange + ['Red']*num_red)

first_bag = Table().with_column('Color',color_list)
first_bag.show()

In [9]:
first_bag.sample(first_bag.num_rows,with_replacement = True)

Color
Green
Orange
Red
Orange
Yellow
Brown
Yellow
Brown
Red
Blue
... (96 rows omitted)